### ISSUE TITLE
Zero division error

### ISSUE THREAD

**Issue by AishaAJ** [tsailabSJ/circleseq#25]
I'm getting this error. 

> [bam_sort_core] merging from 5 files...
> [06/21 03:20:52PM][INFO][alignReads] Sorting for control_U2OS_EMX1_rep_1 by name complete.
> [06/21 03:20:52PM][INFO][circleseq] Finished merging and aligning reads.
> [06/21 03:20:52PM][INFO][circleseq] Identifying off-target cleavage sites.
> [06/21 03:20:52PM][INFO][circleseq] Reads: 4, Window: 3, MAPQ: 50, Gap: 3, Start 1, Mismatches 6
> Writing counts to ./identified/U2OS_EMX1_rep_3_count.txt
> Tabulate nuclease merged start positions.
> 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.0 4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.0 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.0 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.0 8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.0 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9 10.0 10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.0 11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.0 12.1 12.2 12.3 12.4 12.5 12.6 12.7 12.8 12.9 13.0 13.1 13.2 Tabulate control merged start positions.
> 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0 3.1 3.2 3.3 3.4 3.5 [06/21 03:35:04PM][ERROR][circleseq] Error identifying off-target cleavage site.
> [06/21 03:35:04PM][ERROR][circleseq] Traceback (most recent call last):
>   File "circleseq/circleseq/circleseq.py", line 157, in findCleavageSites
>     identified_sites_file, merged=self.merged_analysis)
>   File "/Users/aljanahiaa/runs/circleseq/circleseq/circleseq/findCleavageSites.py", line 577, in compare
>     ecdf_pos = statsmodels.distributions.empirical_distribution.ECDF(bg_position)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/statsmodels/distributions/empirical_distribution.py", line 140, in __init__
>     y = np.linspace(1./nobs,1,nobs)
> ZeroDivisionError: float division by zero

**Comment by AishaAJ** [comment]
Renaming my chromosomes to "1, 2, 3....X" fixed this.

**Comment by shengdar** [comment]
Now all chromosome format names are supported.

**Comment by Akitsu505** [comment]
I am trying to run circleseq.py (downloaded on June 2018), but still getting the same error as above. My reference hg38 and mapped sam/bam files use chr1, chr2, ...chrX, instead of 1, 2, ...X.
Should I change all the chromosome names on bam/sam files? Please let me know how the chromosome format names are supported.

Thanks for developing the nice tool, by the way.

> [07/19 02:03:24PM][INFO][alignReads] Sorting for control_1383D2_CS02_Alu by name complete.
> [07/19 02:03:24PM][INFO][circleseq] Finished merging and aligning reads.
> [07/19 02:03:24PM][INFO][circleseq] Identifying off-target cleavage sites.
> [07/19 02:03:24PM][INFO][circleseq] Window: 3, MAPQ: 50, Gap: 3, Start 1, Mismatches 6, Search_Radius 20
> Writing counts to ./Experimental_data/180717_CIRCLE-seq-analysis/identified/1383D2_CS02_Alu_count.txt
> Tabulate nuclease merged start positions.
> 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0ATabulate control merged start positions.
> 0.1A0.2A0.3A0.4A0.5A0.6A0.7A0.8A0.9A1.0A1.1A1.2A1.3A1.4A1.5A1.6A1.7A1.8A1.9A2.0A2.1A2.2A2.3A2.4A2.5A2.6A2.7A2.8A2.9A3.0A3.1A3.2A3.3A3.4A3.5A3.663.76[]A[]
> [07/19 02:05:38PM][ERROR][circleseq] Error identifying off-target cleavage site.
> [07/19 02:05:38PM][ERROR][circleseq] Traceback (most recent call last):
>   File "./circleseq/circleseq/circleseq.py", line 168, in findCleavageSites
>     identified_sites_file, self.all_chromosomes, merged=self.merged_analysis)
>   File "./circleseq/circleseq/findCleavageSites.py", line 611, in compare
>     ecdf_pos = ECDF(bg_position)
>   File "/anaconda2/lib/python2.7/site-packages/statsmodels/distributions/empirical_distribution.py", line 140, in __init__
>     y = np.linspace(1./nobs,1,nobs)
> ZeroDivisionError: float division by zero
