### ISSUE TITLE
I cannot pip install because version of HTSeq

### ISSUE THREAD

**Issue by PavitaKae** [tsailabSJ/circleseq#44]
I create environment for python2.7 and install BWA, SAMtool is this.
I download circleseq-1.1 and try to pip install.
But i found error.
`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting argparse>=1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting PyYAML>=3.11
  Using cached PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574 kB)
Collecting regex>=2018.01.10
  Using cached regex-2022.1.18.tar.gz (382 kB)
Collecting HTSeq>=0.6.1p1
  Using cached HTSeq-2.0.2.tar.gz (394 kB)
    ERROR: Command errored out with exit status 1:
     command: /tarafs/biobank/data/home/pkaewpro/envs/circleseq2/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FTFxCy/htseq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FTFxCy/htseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-aI9Jyb
         cwd: /tmp/pip-install-FTFxCy/htseq/
    Complete output (2 lines):
    Error in setup script for HTSeq:
    HTSeq requires Python 3.7+.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

why HTseq requires Python 3.7?. How to correct it?

thank you

**Comment by alan-tracey** [comment]
I was able to get HTSeq to install under a python2.7 conda environment using:

**Comment by alan-tracey** [comment]
`RUN conda install -c bioconda htseq`

**Comment by PavitaKae** [comment]
I can install by when create environment, i list all requirement module. conda will find compatible version.
